version: '3.7'
services:
  ci.local:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - isolated_nw
  jenkins:
    build: ./docker/jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "8082:8082"
      - "50000:50000"
    networks:
      - isolated_nw
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    depends_on:
      - sonarqube
  sonarqube:
    build: ./docker/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    command:
      -Dsonar.web.context=/sonarqube
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    networks:
      - isolated_nw
    depends_on:
      - db
  nexus:
    image: "jbuncle/nexus-repository-composer"
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
    networks:
      - isolated_nw
    environment:
      - NEXUS_CONTEXT=nexus
  db:
    image: "postgres:11-alpine"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - isolated_nw
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
networks:
  isolated_nw:
    name: isolated_nw
    driver: bridge
volumes:
  jenkins-data:
    name: jenkins-volume
  postgresql-data:
    name: postgresql-volume
  nexus-data:
    name: nexus-volume
  
    
